### ISSUE TITLE
Error: No constructor for the given network.

### ISSUE THREAD

**Issue by ZHXZHX99** [byminji/SLTtrack#1]
Great work!
When I run LaSOT database by 'python pytracking/run_tracker.py slt_transt slt_transt --dataset_name lasot, there is an error, says "No constructor for the given network. "  And I look up the code, I find in ''ltr/admin/loading.py ", when loading the checkpoint "slt_transt", there is no 'constructor' in 'checkpoint_dict' . So is the given model "slt_transt" not right? 

Thanks for replying.

**Comment by byminji** [comment]
Hi! Thank you for raising the issue. I checked the model 'slt_transt' and found out that the 'constructor' field is missing as you raised. I added the constructor information to some models (slt_transt, transt, slt_trdimp, trdimp) and uploaded them to Google Drive. Please download the new versions and check if you can run the code with the given network.

Thank you.
