### ISSUE TITLE
Inference for custom video

### ISSUE THREAD

**Issue by prsnkmr** [byminji/SLTtrack#2]
Is there any inference script available for inference on custon video,if it is please share it,Thanks in advance

**Comment by byminji** [comment]
Hi,

Unfortunately, we don't provide an inference code for custom videos. However, you could refer to the baseline PyTracking library (https://github.com/visionml/pytracking) to merge the script for running a tracker on a video file.

Thanks.

**Comment by prsnkmr** [comment]
@byminji Thank you so much  for the information
