### ISSUE TITLE
Why in actor you using tracker and self.net but  not only using the self.net?

### ISSUE THREAD

**Issue by AlexDotHam** [byminji/SLTtrack#4]
I'm confused about why you using the tracker and self.net at the same time, and in my opinion, self.net is enough for the whole actors, can you explain for that?

**Comment by AlexDotHam** [comment]
i am not sure about why you using the params.net or params to achieve tracker? i thought self.net is enough for all your work, is that true?

**Comment by byminji** [comment]
Hi, this is because PyTracking library (which is our baseline code) requires params to achieve tracker. We made a minimal modification to implement SLT onto PyTracking for the scalability with other trackers. Please refer to PyTracking (https://github.com/visionml/pytracking) for details.
