### ISSUE TITLE
Problems when run "python setup.py build_ext --inplace"

### ISSUE THREAD

**Issue by Rongzihan** [byminji/SLTtrack#9]
I meet the problem when   run "python setup.py build_ext --inplace" under ${SLTtrack_ROOT}/pysot_toolkit. The problem is reported as below: 

toolkit/utils/region.pyx:185:19: cimported module has no attribute 'compute_polygon_overlap'
Traceback (most recent call last):
  File "/mnt/zihan/SLTtrack-master/pysot_toolkit/setup.py", line 21, in <module>
    ext_modules=cythonize(ext_modules)
  File "/home/zihansr/anaconda3/envs/slt/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
    cythonize_one(*args)
  File "/home/zihansr/anaconda3/envs/slt/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: toolkit/utils/region.pyx

I followed all the previous steps and installed all package well. Could you tell me how to solve this or where can I find the solutions? Thanks!

**Comment by byminji** [comment]
Hi, I tried to rebuild the package from a clean environment but failed to reproduce the error. I guess this might be related to the version issue. I used `Cython==0.28.4`.

**Comment by Rongzihan** [comment]
> Hi, I tried to rebuild the package from a clean environment but failed to reproduce the error. I guess this might be related to the version issue. I used `Cython==0.28.4`.

Thanks, this work for me
